[project]
name = "serial-multi-acm"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "pyserial>=3.5",
    "pyserial-asyncio>=0.6",
    "textual>=8.2.8",
]

[project.scripts]
serial-terminal = "serial_terminal.cli:main"

[build-system]
requires = ["setuptools>=80"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
